# Generated by Django 2.2.10 on 2020-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('balance', models.FloatField(default=0.0)),
                ('PIN', models.IntegerField(default='0700')),
                ('upi_key', models.CharField(max_length=20)),
            ],
        ),
    ]
